import { ipcMain, dialog, BrowserWindow, shell, app } from 'electron'
import * as path from 'path'
import * as fs from 'fs'
import ExcelJS from 'exceljs'
import type { IpcResult } from '../../shared/types'
import { getSupabase } from '../supabase/client'
import { readConfig } from '../store/config'
import { isOnline } from '../store/syncEngine'
import { getLocalDb } from '../store/localDb'
import {
  buildDailyLogWorkbook,
  buildItemSalesWorkbook,
  buildStockReportWorkbook
} from '../excel/workbookBuilders'

export {
  buildDailyLogWorkbook,
  buildItemSalesWorkbook,
  buildStockReportWorkbook
}

/**
 * Returns the ISO timestamp for the very last millisecond of the given month.
 * month format: "YYYY-MM"
 */
function monthEndIso(month: string): string {
  const parts = month.split('-')
  const y = parseInt(parts[0], 10)
  const m = parseInt(parts[1], 10)
  const lastDay = new Date(y, m, 0).getDate()
  return `${month}-${String(lastDay).padStart(2, '0')}T23:59:59.999Z`
}

const recentExportPaths = new Set<string>()

export function recordAllowedExportPath(p?: string | null): void {
  if (p) {
    try {
      recentExportPaths.add(path.resolve(p))
    } catch {}
  }
}

function isAllowedPath(targetPath: string): boolean {
  if (!targetPath || typeof targetPath !== 'string') return false
  if (targetPath.includes('\0')) return false

  let resolved: string
  try {
    resolved = path.resolve(targetPath)
  } catch {
    return false
  }

  // Must not be root drive (e.g. C:\)
  const root = path.parse(resolved).root
  if (resolved === root) return false

  // Never allow Windows or System32 system directories
  const winDir = process.env.WINDIR ? path.resolve(process.env.WINDIR) : null
  if (winDir && (resolved === winDir || resolved.startsWith(winDir + path.sep))) {
    return false
  }

  // If directly generated by an export during this session
  if (recentExportPaths.has(resolved)) return true

  // Check against authorized application directories
  try {
    const cfg = readConfig()
    const allowedRoots: string[] = [
      cfg.saveFolder,
      cfg.backupFolder,
      cfg.inventoryFolder,
    ]
    try { if (app && app.getPath) allowedRoots.push(app.getPath('userData')) } catch {}
    try { if (app && app.getPath) allowedRoots.push(app.getPath('documents')) } catch {}
    try { if (app && app.getPath) allowedRoots.push(app.getPath('downloads')) } catch {}
    try { if (app && app.getPath) allowedRoots.push(app.getPath('desktop')) } catch {}

    return allowedRoots.some(allowed => {
      if (!allowed) return false
      const norm = path.resolve(allowed)
      return resolved === norm || resolved.startsWith(norm + path.sep)
    })
  } catch {
    return false
  }
}

export function registerExportIpc(): void {
  // ── Export Stock Report (Full Relational Workbook) ────────────────────────
  ipcMain.handle('export:stockReport', async (): Promise<IpcResult<string | undefined>> => {
    try {
      const win = BrowserWindow.getFocusedWindow() || undefined
      const dateStr = new Date().toISOString().substring(0, 10)
      const saveRes = await dialog.showSaveDialog(win as any, {
        title: 'Export Stock Report to Excel',
        defaultPath: `STOCK REPORT (${dateStr}).xlsx`,
        filters: [{ name: 'Excel Spreadsheets (*.xlsx)', extensions: ['xlsx'] }]
      })

      if (saveRes.canceled || !saveRes.filePath) {
        return { ok: true, data: undefined }
      }

      const destPath = saveRes.filePath
      const { wb } = await buildStockReportWorkbook(readConfig())
      await wb.xlsx.writeFile(destPath)
      recordAllowedExportPath(destPath)
      return { ok: true, data: destPath }
    } catch (e: unknown) {
      console.error('Failed to export stock report:', e)
      return { ok: false, error: String(e) }
    }
  })

  // ── Export Item Sales Report ──────────────────────────────────────────────
  ipcMain.handle('export:salesReport', async (_e, monthStr: string): Promise<IpcResult<string | undefined>> => {
    try {
      const win = BrowserWindow.getFocusedWindow() || undefined
      const cfg = readConfig()
      const invDir = (cfg.inventoryFolder && fs.existsSync(cfg.inventoryFolder)) ? cfg.inventoryFolder : undefined
      const saveRes = await dialog.showSaveDialog(win as any, {
        title: 'Export Sales Report to Excel',
        defaultPath: invDir ? path.join(invDir, `SALES REPORT (${monthStr}).xlsx`) : `SALES REPORT (${monthStr}).xlsx`,
        filters: [{ name: 'Excel Spreadsheets (*.xlsx)', extensions: ['xlsx'] }]
      })

      if (saveRes.canceled || !saveRes.filePath) {
        return { ok: true, data: undefined }
      }

      const destPath = saveRes.filePath
      const parts = monthStr.split('-')
      const year = parseInt(parts[0], 10)
      const month = parseInt(parts[1], 10)

      const { wb } = await buildItemSalesWorkbook(year, month, cfg)
      await wb.xlsx.writeFile(destPath)
      recordAllowedExportPath(destPath)
      return { ok: true, data: destPath }
    } catch (e: unknown) {
      return { ok: false, error: String(e) }
    }
  })

  // ── Reveal Exported File ──────────────────────────────────────────────────
  ipcMain.handle('export:openFile', async (_e, filePath: string): Promise<IpcResult<void>> => {
    try {
      if (!filePath || typeof filePath !== 'string') {
        return { ok: false, error: 'Invalid file path' }
      }
      const resolved = path.resolve(filePath)
      if (!fs.existsSync(resolved)) {
        return { ok: false, error: 'File not found' }
      }
      if (!isAllowedPath(resolved)) {
        console.warn(`[exportIpc] Blocked export:openFile outside allowed directories: "${resolved}"`)
        return { ok: false, error: 'Access denied: path is outside allowed application directories.' }
      }
      shell.showItemInFolder(resolved)
      return { ok: true, data: undefined }
    } catch (e) {
      return { ok: false, error: String(e) }
    }
  })


  // ── Export Daily Log (Monthly — exact DAILY LOG.xlsx template replica) ────
  ipcMain.handle('export:dailyLog', async (_e, monthStr: string): Promise<IpcResult<string | undefined>> => {
    try {
      const win = BrowserWindow.getFocusedWindow() || BrowserWindow.getAllWindows()[0] || undefined
      const cfg = readConfig()

      if (!monthStr || typeof monthStr !== 'string' || !monthStr.includes('-')) {
        const now = new Date()
        monthStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
      }

      const [yearStr, monthNumStr] = monthStr.split('-')
      const year = parseInt(yearStr, 10) || new Date().getFullYear()
      const monthNum = parseInt(monthNumStr, 10) || (new Date().getMonth() + 1)
      const MONTHS = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']
      const mon = MONTHS[monthNum - 1] || 'JAN'
      const monthPadded = String(monthNum).padStart(2, '0')

      const defaultName = `${monthPadded}. DAILY LOG (${mon})-${year}.xlsx`

      let defaultDir = cfg.saveFolder
      if (!defaultDir || !fs.existsSync(defaultDir)) {
        try {
          defaultDir = app.getPath('documents') || app.getPath('downloads')
        } catch {
          defaultDir = ''
        }
      }

      const saveRes = await dialog.showSaveDialog(win as any, {
        title: 'Export Daily Log to Excel',
        defaultPath: defaultDir ? path.join(defaultDir, defaultName) : defaultName,
        filters: [{ name: 'Excel Spreadsheets (*.xlsx)', extensions: ['xlsx'] }]
      })

      if (saveRes.canceled || !saveRes.filePath) return { ok: true, data: undefined }

      const { wb } = await buildDailyLogWorkbook(year, monthNum, cfg)

      const destPath = saveRes.filePath
      const destDir = path.dirname(destPath)
      if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true })

      await wb.xlsx.writeFile(destPath)
      recordAllowedExportPath(destPath)
      return { ok: true, data: destPath }
    } catch (e: any) {
      console.error('Failed to export daily log:', e)
      const msg = e?.message || String(e)
      if (e?.code === 'EBUSY' || msg.includes('EBUSY')) {
        return { ok: false, error: 'The file is currently open in Excel or another program. Please close Excel and try again.' }
      }
      return { ok: false, error: msg }
    }
  })


  // ── Export Water Audit Log (CSV) ──────────────────────────────────────────
  ipcMain.handle('export:waterLog', async (_e, monthStr: string): Promise<IpcResult<string | undefined>> => {
    try {
      const win = BrowserWindow.getFocusedWindow() || undefined
      const cfg = readConfig()
      const saveDir = (cfg.saveFolder && fs.existsSync(cfg.saveFolder)) ? cfg.saveFolder : undefined
      const saveRes = await dialog.showSaveDialog(win as any, {
        title: 'Export Water Audit Log',
        defaultPath: saveDir ? path.join(saveDir, `audit-${monthStr}.csv`) : `audit-${monthStr}.csv`,
        filters: [
          { name: 'CSV Files (*.csv)', extensions: ['csv'] },
          { name: 'Text Files (*.txt)', extensions: ['txt'] }
        ]
      })
      if (saveRes.canceled || !saveRes.filePath) return { ok: true, data: undefined }

      const sb = await getSupabase()
      const startIso = `${monthStr}-01T00:00:00.000Z`
      const endIso   = monthEndIso(monthStr)

      let rows: { timestamp: string; action: string; details: string }[] = []

      const { data, error } = await sb
        .from('audit_logs')
        .select('action, details, timestamp')
        .eq('log_type', 'water')
        .gte('timestamp', startIso)
        .lte('timestamp', endIso)
        .order('timestamp', { ascending: true })

      if (!error && data && data.length > 0) {
        rows = data.map(r => {
          let ts = r.timestamp
          try { const d = new Date(r.timestamp); if (!isNaN(d.getTime())) ts = d.toISOString().replace('T', ' ').substring(0, 19) } catch {}
          return { timestamp: ts, action: r.action, details: r.details }
        })
      } else {
        // Fallback: try reading from legacy txt backup
        try {
          const cfg = readConfig()
          if (cfg.backupFolder) {
            const logFile = path.join(cfg.backupFolder, 'logs', `audit-${monthStr}.txt`)
            if (fs.existsSync(logFile)) {
              const pattern = /^\[(.*?)\] \[(.*?)\] (.*)$/
              for (const line of fs.readFileSync(logFile, 'utf-8').split('\n')) {
                const m = line.trim().match(pattern)
                if (m) rows.push({ timestamp: m[1], action: m[2], details: m[3] })
              }
            }
          }
        } catch {}
      }

      const csvLines = ['Timestamp,Action,Details']
      for (const r of rows) {
        const esc = (s: string) => `"${(s || '').replace(/"/g, '""')}"`
        csvLines.push(`${esc(r.timestamp)},${esc(r.action)},${esc(r.details)}`)
      }

      fs.writeFileSync(saveRes.filePath, csvLines.join('\r\n'), 'utf-8')
      recordAllowedExportPath(saveRes.filePath)
      return { ok: true, data: saveRes.filePath }
    } catch (e: unknown) {
      return { ok: false, error: String(e) }
    }
  })

  // ── Export Item Sales Audit Log (CSV) ─────────────────────────────────────
  ipcMain.handle('export:itemLog', async (_e, monthStr: string): Promise<IpcResult<string | undefined>> => {
    try {
      const win = BrowserWindow.getFocusedWindow() || undefined
      const cfg = readConfig()
      const invDir = (cfg.inventoryFolder && fs.existsSync(cfg.inventoryFolder)) ? cfg.inventoryFolder : undefined
      const saveRes = await dialog.showSaveDialog(win as any, {
        title: 'Export Item Sales Audit Log',
        defaultPath: invDir ? path.join(invDir, `item-audit-${monthStr}.csv`) : `item-audit-${monthStr}.csv`,
        filters: [
          { name: 'CSV Files (*.csv)', extensions: ['csv'] },
          { name: 'Text Files (*.txt)', extensions: ['txt'] }
        ]
      })
      if (saveRes.canceled || !saveRes.filePath) return { ok: true, data: undefined }

      const sb = await getSupabase()
      const startIso = `${monthStr}-01T00:00:00.000Z`
      const endIso   = monthEndIso(monthStr)

      let rows: { timestamp: string; action: string; details: string }[] = []

      const { data, error } = await sb
        .from('audit_logs')
        .select('action, details, timestamp')
        .eq('log_type', 'item')
        .gte('timestamp', startIso)
        .lte('timestamp', endIso)
        .order('timestamp', { ascending: true })

      if (!error && data && data.length > 0) {
        rows = data.map(r => {
          let ts = r.timestamp
          try { const d = new Date(r.timestamp); if (!isNaN(d.getTime())) ts = d.toISOString().replace('T', ' ').substring(0, 19) } catch {}
          return { timestamp: ts, action: r.action, details: r.details }
        })
      } else {
        try {
          const cfg = readConfig()
          if (cfg.backupFolder) {
            const logFile = path.join(cfg.backupFolder, 'logs', `item-audit-${monthStr}.txt`)
            if (fs.existsSync(logFile)) {
              const pattern = /^\[(.*?)\] \[(.*?)\] (.*)$/
              for (const line of fs.readFileSync(logFile, 'utf-8').split('\n')) {
                const m = line.trim().match(pattern)
                if (m) rows.push({ timestamp: m[1], action: m[2], details: m[3] })
              }
            }
          }
        } catch {}
      }

      const csvLines = ['Timestamp,Action,Details']
      for (const r of rows) {
        const esc = (s: string) => `"${(s || '').replace(/"/g, '""')}"`
        csvLines.push(`${esc(r.timestamp)},${esc(r.action)},${esc(r.details)}`)
      }

      fs.writeFileSync(saveRes.filePath, csvLines.join('\r\n'), 'utf-8')
      recordAllowedExportPath(saveRes.filePath)
      return { ok: true, data: saveRes.filePath }
    } catch (e: unknown) {
      return { ok: false, error: String(e) }
    }
  })

  // ── Export Folder (recursive copy to user-chosen destination) ─────────────
  ipcMain.handle('export:folder', async (_e, srcPath: string): Promise<IpcResult<{ destPath: string; filesCopied: number }>> => {
    try {
      if (!srcPath || typeof srcPath !== 'string') {
        return { ok: false, error: 'Invalid source folder path.' }
      }
      const resolvedSrc = path.resolve(srcPath)
      if (!fs.existsSync(resolvedSrc)) {
        return { ok: false, error: 'Source folder does not exist.' }
      }
      if (!isAllowedPath(resolvedSrc)) {
        console.warn(`[exportIpc] Blocked export:folder outside allowed directories: "${resolvedSrc}"`)
        return { ok: false, error: 'Access denied: source folder is outside allowed application directories.' }
      }
      const win = BrowserWindow.getFocusedWindow() || undefined
      const folderRes = await dialog.showOpenDialog(win as any, {
        title: 'Choose Destination Folder',
        properties: ['openDirectory', 'createDirectory'],
        buttonLabel: 'Export Here'
      })
      if (folderRes.canceled || !folderRes.filePaths[0]) return { ok: true, data: { destPath: '', filesCopied: 0 } }

      const destPath = folderRes.filePaths[0]
      if (destPath === srcPath) return { ok: false, error: 'Source and destination cannot be the same folder.' }

      let filesCopied = 0

      function copyRecursive(src: string, dest: string): void {
        if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true })
        for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
          if (entry.name.startsWith('~$') || entry.name.endsWith('.tmp')) continue
          const srcEntry = path.join(src, entry.name)
          const destEntry = path.join(dest, entry.name)
          if (entry.isDirectory()) {
            copyRecursive(srcEntry, destEntry)
          } else {
            try {
              fs.copyFileSync(srcEntry, destEntry)
              filesCopied++
            } catch {}
          }
        }
      }

      copyRecursive(resolvedSrc, destPath)
      recordAllowedExportPath(destPath)
      return { ok: true, data: { destPath, filesCopied } }
    } catch (e: unknown) {
      return { ok: false, error: String(e) }
    }
  })

  // ── Bulk Year Export ──────────────────────────────────────────────────────
  // Generates all 12 Daily Log + 12 Item Sales workbooks for a given year,
  // saving them directly into a user-chosen folder (no per-file save dialogs).
  ipcMain.handle('export:bulkYear', async (_e, year: number, type: 'dailylog' | 'sales' | 'both' = 'both'): Promise<IpcResult<{ folder: string; filesWritten: number }>> => {
    try {
      const win = BrowserWindow.getFocusedWindow() || BrowserWindow.getAllWindows()[0] || undefined
      const cfg = readConfig()
      const sb = await getSupabase()

      // 1. Let user pick destination folder (default to saved directory)
      const savedDefault = type === 'sales'
        ? ((cfg.inventoryFolder && fs.existsSync(cfg.inventoryFolder)) ? cfg.inventoryFolder : undefined)
        : ((cfg.saveFolder && fs.existsSync(cfg.saveFolder)) ? cfg.saveFolder : undefined)
      const folderRes = await dialog.showOpenDialog(win as any, {
        title: `Choose destination folder for ${year} exports`,
        defaultPath: savedDefault,
        properties: ['openDirectory', 'createDirectory'],
        buttonLabel: `Export ${year} Here`
      })
      if (folderRes.canceled || folderRes.filePaths.length === 0) {
        return { ok: true, data: { folder: '', filesWritten: 0 } }
      }
      const destFolder = folderRes.filePaths[0]

      const MONTHS = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']
      let filesWritten = 0

      // 2. Loop through each month
      for (let monthNum = 1; monthNum <= 12; monthNum++) {
        const mon = MONTHS[monthNum - 1]
        const monthPadded = String(monthNum).padStart(2, '0')
        const daysInMonth = new Date(year, monthNum, 0).getDate()
        const startDate = `${year}-${monthPadded}-01`
        const endDate = `${year}-${monthPadded}-${String(daysInMonth).padStart(2, '0')}`

        // ── A. Daily Refill Log ─────────────────────────────────────────────
        if (type === 'dailylog' || type === 'both') {
          const { wb, hasData } = await buildDailyLogWorkbook(year, monthNum, cfg)
          if (hasData) {
            const dailyLogDestPath = path.join(destFolder, `${monthPadded}. DAILY LOG (${mon})-${year}.xlsx`)
            if (!fs.existsSync(destFolder)) fs.mkdirSync(destFolder, { recursive: true })
            await wb.xlsx.writeFile(dailyLogDestPath)
            filesWritten++
          }
        }

        // ── B. Item Sales Report ───────────────────────────────────────────
        if (type === 'sales' || type === 'both') {
          let salesData: any[] = []
          if (!isOnline()) {
            const db = getLocalDb()
            const raw = db.prepare('SELECT date, quantity, unit_price_at_sale, discount, remarks, item_name, item_code, category_name FROM item_sales_cache WHERE date >= ? AND date <= ? ORDER BY date ASC').all(startDate, endDate)
            salesData = raw.map((r: any) => ({
              date: r.date,
              quantity: r.quantity,
              unit_price_at_sale: r.unit_price_at_sale,
              discount: r.discount,
              remarks: r.remarks,
              items: {
                name: r.item_name,
                code: r.item_code,
                categories: { name: r.category_name }
              }
            }))
          } else {
            const { data } = await sb
            .from('item_sales')
            .select(`id, quantity, unit_price_at_sale, discount, date, remarks, items(name, code, srp, categories(name))`)
            .gte('date', startDate).lte('date', endDate)
            .order('date', { ascending: true }).order('created_at', { ascending: true })
            salesData = data || []
          }


        if (salesData && salesData.length > 0) {
          const salesWb = new ExcelJS.Workbook()
          salesWb.creator = 'A&G Water Refill App'
          salesWb.created = new Date()

          const salesWs = salesWb.addWorksheet(`${mon} ${year} ITEM SALES`, {
            properties: { tabColor: { argb: 'FF6366F1' } }
          })
          salesWs.views = [{ state: 'frozen', ySplit: 2 }]
          salesWs.getColumn(1).width = 5
          salesWs.getColumn(2).width = 30
          salesWs.getColumn(3).width = 18
          salesWs.getColumn(4).width = 12
          salesWs.getColumn(5).width = 12
          salesWs.getColumn(6).width = 12
          salesWs.getColumn(7).width = 14
          salesWs.getColumn(8).width = 14
          salesWs.getColumn(9).width = 20
          salesWs.getColumn(10).width = 14

          salesWs.mergeCells('A1:J1')
          salesWs.getCell('A1').value = `A&G WATER REFILL — Item Sales Report — ${mon} ${year}`
          salesWs.getCell('A1').font = { bold: true, size: 13, color: { argb: 'FFFFFFFF' } }
          salesWs.getCell('A1').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } }
          salesWs.getCell('A1').alignment = { vertical: 'middle', horizontal: 'center' }
          salesWs.getRow(1).height = 26

          const salesHdr = salesWs.getRow(2)
          salesHdr.height = 22
          const salesCols = ['#', 'Item Name', 'Category', 'Code', 'Qty', 'Unit Price', 'Amount', 'Discount', 'Remarks', 'Date']
          salesCols.forEach((h, ci) => {
            const cell = salesHdr.getCell(ci + 1)
            cell.value = h
            cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 }
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } }
            cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true }
            cell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } }
          })

          salesData.forEach((row: any, idx: number) => {
            const ri = idx + 3
            const itemObj = row.items || {}
            const price = Number(row.unit_price_at_sale) || Number(itemObj.srp) || 0
            const qty = Number(row.quantity) || 0
            const discount = Number(row.discount) || 0
            const salesAmount = price * qty
            const salesRow = salesWs.getRow(ri)
            salesRow.height = 17
            salesRow.getCell(1).value = idx + 1
            salesRow.getCell(2).value = itemObj.name || ''
            salesRow.getCell(3).value = (itemObj.categories as any)?.name || ''
            salesRow.getCell(4).value = itemObj.code || ''
            salesRow.getCell(5).value = qty
            salesRow.getCell(6).value = price
            salesRow.getCell(6).numFmt = '₱#,##0.00'
            salesRow.getCell(7).value = salesAmount
            salesRow.getCell(7).numFmt = '₱#,##0.00'
            salesRow.getCell(8).value = discount
            salesRow.getCell(8).numFmt = '₱#,##0.00'
            salesRow.getCell(9).value = row.remarks || ''
            salesRow.getCell(10).value = row.date
            const isEven = ri % 2 === 0
            for (let c = 1; c <= 10; c++) {
              salesRow.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: isEven ? 'FFF5F3FF' : 'FFFFFFFF' } }
              salesRow.getCell(c).border = { top: { style: 'hair' }, bottom: { style: 'hair' }, left: { style: 'thin' }, right: { style: 'thin' } }
            }
          })

          const totRi = salesData.length + 3
          const totRow = salesWs.getRow(totRi)
          totRow.height = 22
          salesWs.mergeCells(`A${totRi}:D${totRi}`)
          totRow.getCell(1).value = 'MONTHLY TOTALS'
          totRow.getCell(1).font = { bold: true }
          totRow.getCell(1).alignment = { horizontal: 'right' }
          totRow.getCell(5).value = { formula: `SUM(E3:E${totRi - 1})` } as any
          totRow.getCell(5).font = { bold: true }
          totRow.getCell(7).value = { formula: `SUM(G3:G${totRi - 1})` } as any
          totRow.getCell(7).numFmt = '₱#,##0.00'
          totRow.getCell(7).font = { bold: true, color: { argb: 'FF1E6600' } }
          totRow.getCell(8).value = { formula: `SUM(H3:H${totRi - 1})` } as any
          totRow.getCell(8).numFmt = '₱#,##0.00'
          totRow.getCell(8).font = { bold: true, color: { argb: 'FFCC0000' } }

          const salesDestPath = path.join(destFolder, `ITEM SALES (${mon})-${year}.xlsx`)
          await salesWb.xlsx.writeFile(salesDestPath)
          filesWritten++
        } // if salesData.length > 0
        } // end if type === sales
      } // end for monthNum

      recordAllowedExportPath(destFolder)
      return { ok: true, data: { folder: destFolder, filesWritten } }
    } catch (e: unknown) {
      console.error('[export:bulkYear]', e)
      return { ok: false, error: String(e) }
    }
  })
}

